# Generated by Django 5.0 on 2024-01-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('pace', models.IntegerField(default=0)),
                ('stamina', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('dribble', models.IntegerField(default=0)),
                ('physique', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football_app.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(('pace__range', (0, 10))), name='pace_range'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(('stamina__range', (0, 10))), name='stamina_range'),
        ),
    ]
