# Generated by Django 5.0 on 2024-01-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_code',
        ),
    ]
